"""Add table rngdle

Revision ID: 27d05d2a61d2
Revises: 0001_create_base_tables
Create Date: 2026-06-13 19:53:17.880214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "27d05d2a61d2"
down_revision: Union[str, Sequence[str], None] = "0001_create_base_tables"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rngdle",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("rng_username", sa.String(length=20), nullable=False),
        sa.Column("date", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "rngdleuser",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("rng_username", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rngdleuser")
    op.drop_table("rngdle")
    # ### end Alembic commands ###
